/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppTabBar: typeof import('./src/components/AppTabBar.vue')['default']
    ArFloatingValueRail: typeof import('./src/components/ar/ArFloatingValueRail.vue')['default']
    ArInfoGrid: typeof import('./src/components/ar/ArInfoGrid.vue')['default']
    ArPanelSection: typeof import('./src/components/ar/ArPanelSection.vue')['default']
    ArPlacementStatusSection: typeof import('./src/components/ar/ArPlacementStatusSection.vue')['default']
    PatrolCard: typeof import('./src/components/PatrolCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UndergroundDisplayControls: typeof import('./src/components/ar/UndergroundDisplayControls.vue')['default']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
